/*
 * Copyright 2018 Litsec AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.litsec.bankid.rpapi.state;

/**
 * The {@code InitiateOperationState} is the first state after the user has selected "this" or "another" device.
 * Dependending on the configuration (requirements) and the user device, the next step may be to require additional
 * input, or to start the operation.
 * 
 * @author Martin Lindström (martin@litsec.se)
 */
public interface InitiateOperationState extends BankIDState<VoidInput> {

  /**
   * Returns {@code false}. This is not an end state.
   */
  @Override
  default boolean isEndState() {
    return false;
  }
  
  /**
   * Returns {@code false}. No input is required for this state.
   */
  @Override
  default boolean isInputRequired() {
    return false;
  }  
  
  /**
   * Returns {@code null}. No output is generated by this state.
   */
  @Override
  default BankIDStateOutput getOutput() {
    return null;
  }

  /** {@inheritDoc} */
  @Override
  default String getStateName() {
    return "initiate-operation";
  }

}
